services:  
  web:    
    build: .    
    ports:      
      - "5000:5000"    
    depends_on:      
      - db

  migrate:  
    build: .  
    depends_on:    
      - db  
    entrypoint: ["/bin/sh", "-c", "./scripts/wait-for-postgres.sh db && python ./check_and_migrate.py"]

  db:
    image: postgres:13
    env_file: .env
    volumes:      
      - pgdata:/var/lib/postgresql/data
      
volumes:  
  pgdata: